### ISSUE TITLE
Non-standard ESMF mod installation (ufs_release_1.0)

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#10]
https://github.com/NOAA-EMC/NCEPLIBS/blob/4eb0b72461e8e07bbf407ea7e13f02f0d4286091/CMakeLists.txt#L591

The ESMF installation that comes with the NCEPLIBS umbrella build installs the `.mod` files in the `include` directory. This is a non-standard installation and doesn't match the NOAA RDHPCS platforms (see, for example on hera: /scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.0.0-intel18.0.5.274-impi2018.0.4-netcdf4.6.1). NOAA RDHPCS ESMF installations are done by the ESMF team, and their recommended way is to place the `.mod` files in the `mod` subdirectory of the ESMF top-level directory.

The implication of this is that when an existing ESMF installation is to be used, the build of packages like NCEPLIBS-post fails, because it is looking for `esmf.mod` in the include directory (instead of the mod directory) underneath the ESMF top-level directory.

I will change the lines above to install the `.mod` files in the `mod` directory. As long as the header files in the include directory are not needed, this should work. Otherwise we need to redefine ESMF_INC so that it can contain a list of directories (`.../mod` and `.../include`)

**Comment by kgerheiser** [comment]
Shouldn't setting `ESMFMKFILE` and running `find_package` resolve where the `.mod` files are located regardless of where they were installed?

**Comment by climbfuji** [comment]
Not unless we change the way how we handle the include directories. ESMFMKFILE contains, for example,
ESMF_LIBSDIR=/usr/local/gnu/esmf-8.0.0/lib
which we can use to compose the variable ESMF_LIB, but it doesn't contain something like ESMF_INCDIR or ESMF_MODDIR. It has:
```
ESMF_F90COMPILEPATHS=-I/usr/local/gnu/esmf-8.0.0/mod -I/usr/local/gnu/esmf-8.0.0/include -I/usr/local/gnu/include
```
but this is not very cmake-y. cmake wants a list of directories and then call include_directories(...) . So what I am doing now, far from ideal, is to use the ESMF_LIBSDIR that we get from the ESMF find_package macro, and define
```
set(ESMF_LIB ${ESMF_LIBSDIR}/${CMAKE_SHARED_LIBRARY_PREFIX}esmf_fullylinked${CMAKE_SHARED_LIBRARY_SUFFIX})
# Note - this only works if the include directory sits next to the lib directory
set(ESMF_INC ${ESMF_LIBSDIR}/../mod)

```

**Comment by climbfuji** [comment]
Fixed by https://github.com/NOAA-EMC/NCEPLIBS/pull/12.
