### ISSUE TITLE
Add Fortran compiler flags for supporting gfortran-10

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#106]
Two items related to this issue:
- Add `gfortran-10` compiler flags 

```
 if(${CMAKE_Fortran_COMPILER_ID} MATCHES "^(GNU)$" AND ${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER_EQUAL 10)
   set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -w -fallow-argument-mismatch -fallow-invalid-boz")
 endif()
```

- Allow specification of compiler flags from the environment e.g. `CFLAGS`, `FFLAGS`

```
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS}  existing_fortran_flags")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  existing_c_flags")
```

List of libraries that need to be updated:

- [x] bacio
- [x] bufr
- [ ] crtm 
- [x] g2
- [x] g2c
- [ ] g2tmpl
- [x] gfsio 
- [ ] grib_util 
- [x] ip
- [x] ip2
- [x] landsfcutil
- [x] nemsio
- [x] nemsiogfs
- [x] prod_util 
- [x] sfcio
- [x] sigio
- [x] sp
- [x] w3emc
- [x] w3nco
- [x] wrf_io

**Comment by aerorahul** [comment]
This should be done in the repos as well. Not everyone uses the umbrella build. And it is especially not used when installing/updating a single or handful of libraries. 

An alternative is to set environment variables.

**Comment by kgerheiser** [comment]
I'll just go through each library and add it

**Comment by aerorahul** [comment]
@kgerheiser 
If you could also add the following:
```
set(CMAKE_Fortran_FLAGS ${CMAKE_Fortran_FLAGS} ...) 
```

The above will allow passing `FFLAGS` from the environment.

Same for `CMAKE_C_FLAGS`.

We can use this with a list of NCEPLIBS and split the work.
