### ISSUE TITLE
Should ip and ip2 libraries be combined?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#122]
There has been talk of combining the ip (https://github.com/NOAA-EMC/NCEPLIBS-ip) and ip2 (https://github.com/NOAA-EMC/NCEPLIBS-ip2) libraries. How would this happen? @GeorgeGayno-NOAA what do you think?

**Comment by GeorgeGayno-NOAA** [comment]
> There has been talk of combining the ip and ip2 libraries. How would this happen? @GeorgeGayno-NOAA what do you think?

First, someone would need to be assigned to the task.  Are you volunteering?

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA yes, of course! ;-)

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA yes, of course! ;-)

More power to you!  Should we set up a brief google meet?  I can tell you what I know about the libraries.

**Comment by edwardhartnett** [comment]
So some important considerations in this decision:
* What libraries, if any, do ip and ip2 depend on?
* Do they depend on each other in any way?
* They seem to be both Fortran code, is that correct?
* Do they have separate user bases? Who uses each of them?

**Comment by GeorgeGayno-NOAA** [comment]
> So some important considerations in this decision:
> 
> * What libraries, if any, do ip and ip2 depend on?

They depend on the sp library.

> * Do they depend on each other in any way?

They are independent.

> * They seem to be both Fortran code, is that correct?

Yes.

> * Do they have separate user bases? Who uses each of them?

IP has been around many years and has many users.  It is also used by our 'copygb' utility, which also has many users.  IP2 is a new library.  So it has very few users.

**Comment by edwardhartnett** [comment]
Seems like I managed to build ip without sp, though sp was required for ip2.

When and why was the new library introduced?

How come the extra functionality of ip2 was not rolled into ip?

Is it intended to retire ip at some point? Or are the two libraries intended to both continue?

**Comment by GeorgeGayno-NOAA** [comment]
> Seems like I managed to build ip without sp, though sp was required for ip2.
> 
> When and why was the new library introduced?
> 
> How come the extra functionality of ip2 was not rolled into ip?
> 
> Is it intended to retire ip at some point? Or are the two libraries intended to both continue?

The idea was ip would be replaced by ip2 when NCO forced everyone to convert from GRIB1 to GRIB2.

**Comment by edwardhartnett** [comment]
The way that you phrase that seems to cast doubt upon it. ;-)

Is NCO forcing everyone to convert to GRIB2? If so, when? When will GRIB1 be retired from processing? 

Does ip2 only deal with GRIB2?

These are the kinds of details that would be best placed in the README. See https://github.com/NOAA-EMC/NCEPLIBS/issues/120.

**Comment by Hang-Lei-NOAA** [comment]
George G: the combined lib should handle both grib1 and grib2.  ip2 lib used more on fortran 90. The way is better to upgrade the ip2 lib to handle grib1.

**Comment by GeorgeGayno-NOAA** [comment]
> George G: the combined lib should handle both grib1 and grib2. ip2 lib used more on fortran 90. The way is better to upgrade the ip2 lib to handle grib1.

For GRIB1 (ip), the grid description information is contained in the KGDS array, which is returned from our GRIB1 library.  For GRIB2 (ip2), the grid description information is contained in IGDTNUM and IGDTMPL, which is returned from our GRIB2 library.   So, the bulk of this project is to map the KGDS entries to the IGDTNUM and IGDTMPL entires or come up with a generic way to contain the grid information for both formats.

**Comment by edwardhartnett** [comment]
How about we simply combine the two existing code bases as is? Instead of making ip2 handle grib1, simply combine the functions of ip and ip2 into one library.

The ip2 code can be in Fortran 90 and the ip code in F77. THat's not a problem. Future work can us F90 and the F77 code can just be left alone.

**Comment by edwardhartnett** [comment]
OK, I am looking at ip now, and it seems to be F90 code...

**Comment by edwardhartnett** [comment]
I've taken a look at ip and ip2. I agree with @kgerheiser there is a lot of duplicate code.

Seems like it would be good to take the extra code from ip2 and move it into ip, then to deprecate ip2 for the next release.

**Comment by edwardhartnett** [comment]
I also see this in the top-level CMake file:

```
# ip and ip2 cannot coexist in a flat structure because they share module names which overwrite each other
if(NOT FLAT)
  list(APPEND _comps ip2)
endif()
```

This seems like another strong argument to combine these two libraries.

@GeorgeGayno-NOAA what parts of ip2 are different from ip? That is, what files in ip2 would have to be brought over to ip?

There are a lot of code files in ip2 with the same names as in ip. Are these just copies or are there changes?

**Comment by GeorgeGayno-NOAA** [comment]
> I also see this in the top-level CMake file:
> 
> ```
> # ip and ip2 cannot coexist in a flat structure because they share module names which overwrite each other
> if(NOT FLAT)
>   list(APPEND _comps ip2)
> endif()
> ```
> 
> This seems like another strong argument to combine these two libraries.
> 
> @GeorgeGayno-NOAA what parts of ip2 are different from ip? That is, what files in ip2 would have to be brought over to ip?
> 
> There are a lot of code files in ip2 with the same names as in ip. Are these just copies or are there changes?

I think the only unique routine in ip2 is "earth_radius.F90".  

The files with the same names are very close, but not exact copies.  The ip2 routines use the grib2 grid description template ("IGDTNUM", "IGDTMPL", "IGDTLEV").  The ip routines use the grib1 grid template ("KGDS").   Coming up with some general way to pass the grid information to all routines is 90% of this project.

For more information on the grib1 and grib2 standards, see:
https://www.nco.ncep.noaa.gov/pmb/docs/on388/
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/

**Comment by edwardhartnett** [comment]
Do the functions for grib2 have the same names as the functions for grib1?

**Comment by edwardhartnett** [comment]
The latest on this is that Kyle changed ip2 to no longer use the same names. 

Now the libraries can be combined.

**Comment by edwardhartnett** [comment]
The libraries have been combined. I will close this issue.
