### ISSUE TITLE
Combine w3emc and w3nco libraries

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#124]
Should we create a new, third library?

Or combine the functions from one into the other?

Which library has more users?

**Comment by Hang-Lei-NOAA** [comment]
combine into a  w3 library

**Comment by Hang-Lei-NOAA** [comment]
Kyle, cycled dependency between two libraries.

**Comment by edwardhartnett** [comment]
Who wants to take this on and create the new w3 library?

**Comment by Hang-Lei-NOAA** [comment]
I can work with Boi to get it done.
Hang

**Comment by BoiVuong-NOAA** [comment]
We should create  a new  and name it as w3 library. The W3EMC has more users.

**Comment by edwardhartnett** [comment]
Why not combine the w3nco into w3emc? Then w3emc users will not have to change anything.

**Comment by Hang-Lei-NOAA** [comment]
There are many code only use w3nco.

**Comment by Hang-Lei-NOAA** [comment]
We can create the w3 lib. and ask users to replace both w3emc and w3nco
usage with w3. All three libs will be available for a period of transition
time. This will be a seamless process.

**Comment by BoiVuong-NOAA** [comment]
I agree with Hang.  Once, we announce to combine w3emc and w3nco into new w3, all users will need to change their scripts or module load any way.

**Comment by edwardhartnett** [comment]
I do not agree.

What is the reason for creating a new library project? That is the opposite of what we are trying to do.

Instead, how about we simply move the code from w3nco into w3emc.

If you later want to change the name of w3emc to w3, that can be done. It does not require a new project be introduced. I would very much like to reduce the proliferation of repos and projects. Each one adds extra work, so needs to also provide benefit. I don't see the benefit here of creating a new project.

**Comment by BoiVuong-NOAA** [comment]
Yes, You are right.  There will be another new repo for w3. We will move the code from w3nco into w3emc.

**Comment by Hang-Lei-NOAA** [comment]
Right, agree!
The work will be done like Boi said.
Hang

**Comment by edwardhartnett** [comment]
OK, I'm a bit confused. Are we all in agreement that the code from w3nco should be moved into w3emc, and no new repo should be created?

**Comment by BoiVuong-NOAA** [comment]
I agree to move the code from w3nco into w3emc.

**Comment by edwardhartnett** [comment]
This has been completed.
