### ISSUE TITLE
Return global events code from w3emc to PREP

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#125]
There is some global events code in w3emc. There is only one user. Can we hand the code off to the user? (@Hang-Lei-NOAA can you add more detail here please?)

**Comment by Hang-Lei-NOAA** [comment]
This need further discussion with obspro group.
I have communicated with them. It seems that they still want to keep it in w3 library.

**Comment by edwardhartnett** [comment]
Should we just close this issue? Or is there hope they will take this code? Should we involve Arun in this discussion?

**Comment by Hang-Lei-NOAA** [comment]
Agree. close it.
