### ISSUE TITLE
Deprecate nemsiogfs, remove it from global-chgRes and any other utility that uses it

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#126]
Should nemsiogfs be removed from NCEPLIBS?

**Comment by Hang-Lei-NOAA** [comment]
As far as I know, after the fv3gfs is used. The only code using nemsiogfs is the global-chgRes.
We can remove this from code level.

George V: it is loaded/used by many code as a historical setup. We may have to modify the modules to see the effects.

**Comment by edwardhartnett** [comment]
OK, sounds like it should not be removed. Should it be merged with nemsio?

**Comment by Hang-Lei-NOAA** [comment]
No, this just use nemsio for GSM. However, no one in EMC use GSM now.

**Comment by edwardhartnett** [comment]
What is GSM?

**Comment by Hang-Lei-NOAA** [comment]
The GSM is the retried GFS dycore before fv3 come in.

**Comment by edwardhartnett** [comment]
OK, so to summarize: the nemsiogsf library deals with data in NEMS format from the GFS model. However, we do not use NEMS any more, we use netCDF-4 (yeah!), and we do not use the GFS any more, we use FV3.

However, this library is linked to a bunch of other software, including global-chgRes, as a part of their historical cababilities, which we don't have to support  moving forward.

So the answer, as originally outlined by @Hang-Lei-NOAA (but it took me a while to understand) is that this library should be deprecated, and we should remove it from all the other software that uses it.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA where is the global-chgRes code?

Also how are we going to identify other software that uses nemsiogfs?

**Comment by Hang-Lei-NOAA** [comment]
The global_chgres is kept on
https://github.com/NOAA-EMC/UFS_UTILS/tree/develop/sorc/global_chgres.fd
It may occur somewhere else. It was a Utility code in GFS.

If the nemsiogfs library is used. Then in the code:
The NEMSIO_GFS is loaded for the code
This is the way to identify where the library is used.

**Comment by edwardhartnett** [comment]
Are UFS_UTILS part of our team? Or is this managed by a different group?

**Comment by Hang-Lei-NOAA** [comment]
It is not a part of NCEPLIBS.
I am not sure which it belongs to now. It used to be a part of GFS.

**Comment by edwardhartnett** [comment]
We will mark this for soft deprecation for now.

**Comment by edwardhartnett** [comment]
This has been accomplished. I will close this issue.
