### ISSUE TITLE
Problems building on NASA platform

### ISSUE THREAD

**Issue by tclune** [NOAA-EMC/NCEPLIBS#13]
This is a summary of the issues that I encountered trying to build from the instructions on NASA's discover cluster using the following modules:
```script
tclune@discover32:/discover/swdev/tclune/NOAA/NCEPLIBS/build> module list
Currently Loaded Modulefiles:
  1) other/git                               3) other/manage_externals                  5) other/comp/gcc-6.3                      7) mpi/impi-18.0.5.274                     9) other/python/GEOSpyD/Ana2019.03_py2.7
  2) other/cmake                             4) GEOSenv                                 6) comp/intel-18.0.5.274                   8) lib/mkl-18.0.5.274
```

[cmake.log](https://github.com/NOAA-EMC/NCEPLIBS/files/4036950/cmake.log)
[make.log](https://github.com/NOAA-EMC/NCEPLIBS/files/4036953/make.log)

Note:   the instructions indicated that the ESMF comm should be "intel", but I used "intelmpi" which I think is correct for ESMF.

**Comment by climbfuji** [comment]
Looks like a missing dependency on the png library in EMC_post. We are currently making a round of updates and once the PRs are merged (see https://github.com/NOAA-EMC/NCEPLIBS/pull/12) I would encourage you to try it again ... thanks for your feedback and efforts thus far!

**Comment by climbfuji** [comment]
We just merged https://github.com/NOAA-EMC/NCEPLIBS/pull/12. Can you try this again, please, using the ufs_release_1.0 branch? libpng should be built as a dependency if needed.
```
git clone -b ufs_release_1.0 --recursive https://github.com/NOAA-EMC/NCEPLIBS
```
By the way, the top-level CMakeLists.txt in this branch is referring to intelmpi for ESMF.

**Comment by tclune** [comment]
Note: there is no branch "ufs_release_1.0", but presuming that you meant "ufs_release_v1.0"  I found the same results as before.    Note that libpng is being built:
```script
   /discover/swdev/tclune/NOAA/NCEPLIBS/build/install/lib/libpng:
  total used in directory 48 available 1425273856
  drwx------ 2 tclune g0620  512 Jan  9 09:04 .
  drwxr-xr-x 3 tclune g0620 8192 Jan  9 09:11 ..
  -rw-r--r-- 1 tclune g0620 3480 Jan  9 09:04 libpng16.cmake
  -rw-r--r-- 1 tclune g0620 1222 Jan  9 09:04 libpng16-release.cmake
```
and
```script
  /discover/swdev/tclune/NOAA/NCEPLIBS/build/install/lib64:
  total used in directory 297696 available 1425273856
  drwx--S---  4 tclune g0620     8192 Jan  9 09:26 .
  drwx--S--- 12 tclune g0620      512 Jan  9 09:26 ..
  drwx--S---  4 tclune g0620      512 Jan  9 09:08 cmake
  -rw-------  1 tclune g0620     8052 Jan  9 09:26 esmf.mk
...
  -rw-r--r--  1 tclune g0620   565622 Jan  9 09:25 libpng16.a
  lrwxrwxrwx  1 tclune g0620       14 Jan  9 09:04 libpng16.so -> libpng16.so.16
  lrwxrwxrwx  1 tclune g0620       19 Jan  9 09:04 libpng16.so.16 -> libpng16.so.16.34.0
  -rwxr-xr-x  1 tclune g0620   377662 Jan  9 09:04 libpng16.so.16.34.0
  lrwxrwxrwx  1 tclune g0620       10 Jan  9 09:04 libpng.a -> libpng16.a
  lrwxrwxrwx  1 tclune g0620       11 Jan  9 09:04 libpng.so -> libpng16.so
  drwx--S---  2 tclune g0620      512 Jan  9 09:08 pkgconfig
```

**Comment by climbfuji** [comment]
Maybe it's got to do with libpng ending up in lib64 on your system? The NCEPLIBS-g2 library has the
find_package(PNG REQUIRED) 
dependency. Could you print out the variables that this call sets right afterwards, please? See https://github.com/Kitware/CMake/blob/master/Modules/FindPNG.cmake . Specifically, let's look for (explanations are from the above website, ignore the add_definitions instructions for the moment)
- `PNG_INCLUDE_DIRS`  where to find png.h, etc.
- `PNG_LIBRARIES`  the libraries to link against to use PNG.
- `PNG_DEFINITIONS` You should add_definitions(${PNG_DEFINITIONS}) before compiling code
  that includes png library files.
- `PNG_FOUND` If false, do not try to use PNG.
- `PNG_VERSION_STRING`

Thanks!

**Comment by tclune** [comment]
Adding the message() statements to the CMakeLists.txt file did not trigger CMake for that library to reprocess.   Rather than trying to understand how the system interlinks the various packages, I'm blowing the build away and starting over with a serial build.    But if there is a better way to reset a single package, please let me know for the future.

**Comment by tclune** [comment]
Very confused now.   My second attempt, where the only change was with the message() statements appeared to have completed cleanly while I was at lunch.     The big difference would seem to be that the second build was done without "-j" parallelism.      Hopefully that is the issue, or we have a more serious non-reproducibility issue.

For the record here i the extra output that was requested:

```script
PNG_INCLUDE_DIRS: /usr/include;/usr/include
PNG_LIBRARIES:    /usr/lib64/libpng.so;/usr/lib64/libz.so
PNG_DEFINITIONS:  
PNG_FOUND:        TRUE
PNG_VERSION_STRING:  1.2.31
```

I don't have time this afternoon, but tomorrow I'll try to do multiple serial and parallel builds to see if there is any consistency.

**Comment by climbfuji** [comment]
So it seems that libpng should not have been built in the first place if it is already installed on the system. Can you check if it was still built but just not used? Thanks!

**Comment by climbfuji** [comment]
Following up. Have you tried the official release tags of NCEPLIBS-external and NCEPLIBS on the NASA platform? If yes, does it work? If this ticket is no longer relevant, please close it. Thanks!

**Comment by tclune** [comment]
Well, it worked well enough for that immediate action.   (We were exploring whether we had a suitable environments for development of code that coupled in some NASA components.)   I'll close for now and reopen if/when the work begins in earnest.
