### ISSUE TITLE
All NCEPLIBS must have unit tests, and use continuous integration with GitHub actions

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#130]
All NCEPLIBS repos must have testing. All must use CI with GitHub actions for testing.

A reasonably complex example, which builds and uses HDF5 and netCDF, can be found here:
https://github.com/NCAR/ParallelIO/blob/master/.github/workflows/a4.yml

**Comment by BenjaminTJohnson** [comment]
For CRTM, specifically, we're working on getting this done over the next month.   

We have multiple build support requirements due to CRTM being integrated in multiple model platforms.

**Comment by edwardhartnett** [comment]
Almost all projects in NCEPLIBS already have CI with GitHub actions, which is great. But most of them are running no tests, which is the next area we need to improve.

**Comment by GeorgeGayno-NOAA** [comment]
IP and IP2 have tests.  But I don't know if they are working.  I think @kgerheiser is working on this.

**Comment by kgerheiser** [comment]
I'm currently in the process of porting ip and ip2's tests to CMake

**Comment by BenjaminTJohnson** [comment]
I'll be providing a cmake build for CRTM within the "next couple of weeks".  We have a code release coming up soon, once that's done, I'll work with the team to get linked to our releases and work out any build/test issues.

**Comment by edwardhartnett** [comment]
To measure code coverage, compile like this:
```
cmake -DCMAKE_Fortran_FLAGS="-fprofile-arcs -ftest-coverage" -DENABLE_TESTS=ON .. && make clean && make VERBOSE=1 && make test
gcovr -r ../ . --html --html-details -o example-html-details.html
```

**Comment by jbathegit** [comment]
Even though we didn't get to them during today's shortened NCEPLIBS meeting, here are my testing notes and tips: https://docs.google.com/document/d/1-vD24bjNcJTXGeu4rAHhJ9u_S7WcUmd75vX2wrFik88/edit?usp=sharing

**Comment by edwardhartnett** [comment]
We will go over these at the next NCEPLIBS meeting. I look forward to it!

**Comment by edwardhartnett** [comment]
We now have at least some unit tests, and good CI, on all active NCEPLIBS projects. I will close this issue.
