### ISSUE TITLE
Change cmake to properly do make and make install 

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#134]
When I do a make at the NCEPLIBS level, it seems to try and install the libraries.

Of course "make" should just build the libraries. "make install" should be required to install them.

**Comment by aerorahul** [comment]
You are right. 
This repo is a convenience to build and install all NCEPLIBS components in one step. 

One can add `STEP_TARGETS build` to the external project macro and it will only build with `make`

One will have to do more to install via `make install`

**Comment by edwardhartnett** [comment]
OK, this is incorrect behavior.

We need make to just make it, not try and install it.

Let us make STEP_TARGETS build be the default behavior, and fix make install so that it does the installation.

**Comment by edwardhartnett** [comment]
SInce hpc-stack and spack-stack have taken over for the NCEPLIBS build, I will close this issue.
