### ISSUE TITLE
g2c is not in our readme list of packages

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#135]
Not built in NCEPLIBS. Is this being used anywhere? @BoiVuong-NOAA do you know if anyone is using this code.

**Comment by BoiVuong-NOAA** [comment]
Yes, The g2c is not in nceplibs.  NCO (developer) has G2C in C to support users who are not using the G2 FORTRAN.  Most of G2C users are GRADS, NASA, some companies, etc.  Some times, I received some helps from outside users (I do not know exactly who were they ?). I assisted them to compile or answered any questions or updated some PDT and GDT tables in GRIB2.

**Comment by edwardhartnett** [comment]
When you say "NCO" do you mean the NOAA branch or the NetCDF Command Operators?

**Comment by edwardhartnett** [comment]
OK, so g2c is not part of NCEPLIBS and not part of our refactoring, testing, and documentation campaign either. At least, not this time around. ;-)
