### ISSUE TITLE
questions about NCEPLIBS-sigio - should it be deprecated, who manages it, what software uses it?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#136]
The NCEPLIBS-sigio package is just two Fortran code files. Does it really need its own library for this? Can't we combine this with one of the other io libraries?

**Comment by edwardhartnett** [comment]
OK, we'll leave this for this refactor...

Discussed this with Kyle and Hang and this code is needed and will continue to be needed.

**Comment by edwardhartnett** [comment]
Who is code manager for this repo? @kgerheiser is it you?

Do we have an idea where the sigio code is used?

**Comment by edwardhartnett** [comment]
Also, we say in the README:

`Does something with Spectral Coefficients.`

Can we be more specific? Do we even know? ;-)

**Comment by edwardhartnett** [comment]
OK, we now say this in the readme: 

> This library provides an Application Program Interface for performing I/O on the sigma restart file of the global spectral model. Functions include opening, reading, writing, and closing as well as allocating and deallocating data buffers used in the transfers. The I/O performed here is sequential. The transfers are limited to header records or data records.

Was the global spectral model part of the GFS? Is this restart file still used?

**Comment by GeorgeGayno-NOAA** [comment]
chgres_cube (of the UFS_UTILS repo) uses the sigio library.  It is used to process restart files from the old spectral model (GFS v13 and earlier - prior to Jul 2017).   So we need to keep it.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA should you or @kgerheiser be the code manager here?
