### ISSUE TITLE
NCEPLIBS-gfsio just one code file

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#138]
Do we need a whole library for this?

**Comment by edwardhartnett** [comment]
Only used in a few places, as an option in post for example. We would have to ask them to remove it. @Hang-Lei-NOAA will ask via email and report back.

**Comment by GeorgeGayno-NOAA** [comment]
The global_chgres code (of UFS_UTILS) also uses it.  However, global_chgres is obsolete and will be removed.

**Comment by edwardhartnett** [comment]
We will mark this for soft deprecation.
