### ISSUE TITLE
Host-dependent information in top-level CMakeLists.txt (and possibly other cmake modules)

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#14]
The top-level `CMakeLists.txt` file in the `ufs_release_1.0` branch contains host-model dependent information at the very top, i.e. in the block starting with line 

https://github.com/NOAA-EMC/NCEPLIBS/blob/c05236ec666a5bd4d91beb96e7921b8049fb524e/CMakeLists.txt#L3

Do we want to keep this? I'd be in favor of removing this information and tell the user in the instructions to set `CC`, `FC`, and other required environment variables as needed for their system.

The same may be true for the `FindNETCDF.cmake` file in the CMakeModules repository. In my opinion, this should look for the environment variable `NETCDF` only, nothing else.

**Comment by kgerheiser** [comment]
I think it should be removed

**Comment by climbfuji** [comment]
Related issue for CMakeModules: https://github.com/NOAA-EMC/CMakeModules/issues/5

**Comment by climbfuji** [comment]
The host-model dependent information has been removed entirely.
