### ISSUE TITLE
Is NCEPLIBS-nemsio to be deprecated?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#140]
I believe this was mentioned, but there is no issue yet, so here is is.

I believe NEMS is going away? True?

Will this library go away too? If so, when?

**Comment by Hang-Lei-NOAA** [comment]
No issue for this. It is still used.
Current modeling frame is developed two generations above NEMS frame.
But the io/data format is still used. There is no date for this to be out.
