### ISSUE TITLE
document wgrib2 and its many issues

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#142]
wgrib2 is a special case in that we get this code periodically (@kgerheiser how often?) from Wesley(?) at the CPC. It is apparently not kept on Git there.

Also it has a home-rolled build system that interferes with the rest of the NCEPLIBS builds. Specifically it tries to have its own version of dependent packages, like netCDF, which it has copied the source from, at attempts to build from scratch. 

So we have in NCEPLIBS-wgrib2 is a copy of this original code, and also a branch which contains the changes made to make it work in the NCEPLIBS build.

What we are going to do is to make the cmake build branch the default branch, and clean it up and maintain it. The source code will be kept in (as best we can manage) it's original directories and format, to make merging new changes possible.

Once we clean up the repo situation, we will take a look at testing...

**Comment by edwardhartnett** [comment]
Here's part of an email from Wesley Ebisuzaki, explaining some of the peculiarities of wgrib2:

>    Wgrib2 has been compiled for configurations outside of our norms.  It is probably
> easier for someone to change the makefile rather than go through CMake.
> 
>     ARM (raspberry pi)
>     MacOS
>     Solaris 10
>     AOCC (clang, flang) on linux
>     open64 on linux
>     gcc/g95 on linux
>     aix  (old)
>     hp  (old)
>     windows (cygwin)
>     inside a aircraft simulator (no details)
> 
>    Wgrib2 includes (or downloads) the various required libraries rather than using system defaults.
> This avoided some (historical) problems.
> 
>     g2clib:  When wgrib2 used g2clib for grid decoding:
>                 It would take 6 months to 12+ months for the changes to get into a ncep public release.
>                 Unacceptable for people who are using weather data.
> 
>     spectral library:  Until recently splib included routines from Numerical Recipes.
>                The current spectral library includes code with an unknown origin.
>                I did not distribute this library with wgrib2 as it would be unacceptable for
>                  inclusion in a public archive.
>               (Note: wgrib2 v3.0.0 comes with an incomplete version of splib.)
> 
>     ip library:  needed changes so the spectral library is not called.  Some changes
>               were needed because of changes in a newer intel compiler.  I needed
>               to add an option to compile with the HWRF version of iplib for use by
>               HWRF users.
> 
>     libpng:   Need a special compile to increase the buffer size to enable a bitmap
>                for radar grib files from Boulder.
> 
>     jasper:  A bug in the jasper library would seg fault for large grids.  A Ubuntu/debian
>              security release fixed the bug.  By including the updated library, the seg fault
>              was solved for all machines.  (The problem was not fixed in the opn phase 1 version.)
> 
> By building the libraries when compiling wgrib2, problems could be fixed in a timely manner.
> With the makefile, building is done with a consistent set of libraries compiled by a known
> compiler with known compile flags.  This is safer for the user.
>

**Comment by edwardhartnett** [comment]
More answers from Wesley:

> 
> The source code is located at
> 
>    https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/
> 
> BTW wgrib2 v3.0.0 was recently released.  I would wait a few months for bug reports
> before implementing it on  the WCOSS.
> 
> A distribution maintainer requested that I keep the old versions online as well as make a
> version without the libraries.
> 
> I understand that EMC needs to go with a CMake build.  I don't have the intention
> of going to CMake because
> 
>    1) I am not familiar with CMake
>    2) Anybody who wants to port wgrib2 to a new compiler or cpu would have
>          a harder job with a CMake system.
>    3) CMake is not universal.  If it were universal, I could type cmake on my NCEP linux box
>            and it would work.  Some users work in environments where the system admins are
>            worse than NCO for installing software. 
>    4) CMake versions matter.  I wanted to compile a library with CMake, and the only CMake
>           that I had access to was on the R&D supercomputer.  It didn't work because
>           the cmake was too old. 
>    5) The makefile works and it is easy to support.
> 
> The current CMake build is good for the NOAA HPC environment, and you have a good
> way of distributing the code and building system to the NOAA community. 
> 
> A major factor in distributing code is my limited time.  I am the only person who supports wgrib2.
> So after the documentation is written, there should be no questions.  By having the CMake
> version on a NOAA github system, a more qualified person gets the questions.
> 
> I have a testing script which gets updated for new features and
> testing bug fixes.
> 
> There is only one developer working on the development version.  People
> submit changes (usually 1-3 submissions a year) which get integrated into
> the development version by hand. 
>

**Comment by edwardhartnett** [comment]
Another issue is lack of support for netCDF-4. From README.netcdf4:

> NetCDF4 support has been in shambles for many years.  The good news,
> Redhat with its vintage compilers has been working fine. If you
> are using the Intel compilers, it compiles and probably works.
> (I have heard no complaints but number of users is extremely small.)

Since all the FV3 output is NetCDF/HDF5 files (a.k.a. NetCDF-4 files) this seems like a problem.

**Comment by kgerheiser** [comment]
NetCDF-4 support is fine, as far as I know. 

I've been compiling and using wgrib2 with NetCDF-4 (CMake build) for a while and have never seen a problem.

**Comment by edwardhartnett** [comment]
The library is used in UFS_UTILS, the executable is used widely, including in several operational workflows. The plan is that our binary build will be used by everyone.

**Comment by edwardhartnett** [comment]
We have removed wgrib2 from UFS_UTILS and it will not be used by any NCEPLIBS. We discourage it's use in any operational systems, due to problems with its build.

We will not be working on the wgrib2 build system any further, since our last extensive effort was discarded.
