### ISSUE TITLE
NCEPLIBS-landsfcutil can be retired

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/NCEPLIBS#145]
This library is only used by UFS_UTILS programs global_chgres and emcsfc_snow2mdl.  The former is being replaced by chgres_cube.  The latter only uses a few small routines from that library.  Those small routines could be included as part of the emcsfc_snow2mdl code.

**Comment by edwardhartnett** [comment]
When is global_chgres being removed?

**Comment by GeorgeGayno-NOAA** [comment]
> When is global_chgres being removed?

I should add that there is a version of global_chgres outside of UFS_UTILS under 'util_shared'.  On Dell, it is here: /gpfs/dell1/nco/ops/nwprod/util_shared.v1.1.2

There is no hard date to remove it.  My thought:  Refuse to port any versions of global_chgres to the new WCOSS machine and see if anyone yells.  If for some reason they can't switch to chgres_cube, then I suppose we will need to continue to support global_chgres and landsfcutil.

**Comment by edwardhartnett** [comment]
OK, how about we mark this for soft deprecation. That is, we won't do work on it and we advise people to not use it in new code, but we will continue to provide it as is, for at least the next year of NCEPLIB releases. Make sense?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, how about we mark this for soft deprecation. That is, we won't do work on it and we advise people to not use it in new code, but we will continue to provide it as is, for at least the next year of NCEPLIB releases. Make sense?

That makes sense.

**Comment by GeorgeGayno-NOAA** [comment]
This library is being removed from UFS_UTILS snow2mdl program under this issue:
https://github.com/NOAA-EMC/UFS_UTILS/issues/169

**Comment by edwardhartnett** [comment]
This has been done.
