### ISSUE TITLE
Requested changes in support of SRW App

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#150]
The SRW App wants an easier way to set environment variables or load modules than loading individual NCEPLIBS modules etc. This was discussed at length in last week's SRW App build team meeting. It was decided to augment the NCEPLIBS with an umbrella modulefile (for systems that use modules) and shell scripts (bash and tcsh; for users on commodity systems without the module environment). This is similar to what was done for the MRW App release.

The approach taken here:

use the existing logic to deploy modulefiles and extend it with an umbrella module and two shell scripts
for simplicity, DEPLOY is by default ON and running make deploy will always overwrite existing files
also add CC, CXX, FC to the umbrella modulefile and the shell scripts; if this is not to be included, we can revert adding CXX to the cmake project languages - should it be removed?
extend lua2tcl.py so that the umbrella modulefile can also be converted
not included yet: scan currently loaded modules and add those (either as module load or prereq) to the umbrella module file - should it be included?
not included yet: search for known dependencies for the app to build (NetCDF, Jasper, ESMF, ...) in the umbrella CMakeLists.txt and add to the umbrella modulefile and shell scripts - should it be included?

**Comment by climbfuji** [comment]
> The SRW App wants an easier way to set environment variables or load modules than loading individual NCEPLIBS modules etc. This was discussed at length in last week's SRW App build team meeting. It was decided to augment the NCEPLIBS with an umbrella modulefile (for systems that use modules) and shell scripts (bash and tcsh; for users on commodity systems without the module environment). This is similar to what was done for the MRW App release.
> 
> The approach taken here:
> 
> use the existing logic to deploy modulefiles and extend it with an umbrella module and two shell scripts
> for simplicity, DEPLOY is by default ON and running make deploy will always overwrite existing files
> also add CC, CXX, FC to the umbrella modulefile and the shell scripts; if this is not to be included, we can revert adding CXX to the cmake project languages - should it be removed?
> extend lua2tcl.py so that the umbrella modulefile can also be converted
> not included yet: scan currently loaded modules and add those (either as module load or prereq) to the umbrella module file - should it be included?
> not included yet: search for known dependencies for the app to build (NetCDF, Jasper, ESMF, ...) in the umbrella CMakeLists.txt and add to the umbrella modulefile and shell scripts - should it be included?

Thanks, @edwardhartnett I could have (and should have) done that myself. Will do better next time,

**Comment by edwardhartnett** [comment]
Has this work been completed? Should this issue be closed?

**Comment by climbfuji** [comment]
This work was completed in release/public-v2. It's not in develop and per @aerorahul it won't go there. In release/public-v2, we also converted all lua modulefiles to tcl modulefiles, because at that time we didn't have lua support on gaea (which we now do).
