### ISSUE TITLE
Remove notifications of unsupported compilers

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#155]
We have these in many cmake files, like this:

```
if(NOT CMAKE_C_COMPILER_ID MATCHES "^(Intel|GNU|AppleClang|Clang)$")
  message(WARNING "Compiler not officially supported: ${CMAKE_C_COMPILER_ID}")
endif()

```

There is no need for this, for several reasons:
* Fortran and C are highly standardized. Every Fortran compiler that works can build these codes.
* Users already understand that if they are working with an unusual compiler, they are taking risks.
* This is no "officially supported" compiler, because we don't officially support the code at all.
* As we already clearly say in our READMEs: "The United States Department of Commerce (DOC) GitHub project code is provided on an "as is" basis and the user assumes responsibility for its use." 
* It is not common practice among scientific software projects.

Instead, we demonstrate that our code works with GNU compilers on the GitHub actions. If we want to list other compilers you have also tested on in the docs or readme, that's fine.

**Comment by aerorahul** [comment]
even PGI? XLF?
The compiler flags that are set are based on the supported compilers?

I know who to pass the buck when a question comes along.

**Comment by edwardhartnett** [comment]
The buck stops here. ;-)

**Comment by kgerheiser** [comment]
I don't think it's a bad warning to have, CMake could pick up one of those compilers automaticall, and we don't have flags for those unsupported compilers. 

The builds will not work because we need to set things like '-fdefault-real-8` when we build the different library kinds.

**Comment by edwardhartnett** [comment]
This is always the case with all free software. Users know this, we know this, and we already tell everyone that we are not providing official support. So no need to belabor the point.

If any actual users complain, direct them to me and I will sort them out.

**Comment by aerorahul** [comment]
I have to disagree.
Having these few lines saves a lot of headache and I suggest we retain those.

**Comment by edwardhartnett** [comment]
I believe this has been done everywhere. I will close this issue.
