### ISSUE TITLE
install upp lib on cray

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/NCEPLIBS#167]
We are merging GFS.v16 production branch back to ufs-weather-model develop branch. The nceppost lib is renamed to upp in GFS.v16. Currently the upp lib is added to hpc-stack, and we tested it on hera/orion/dell. But on cray, there is no hpc-stack. So we need the upp lib to be installed under /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS_UFS/modules, where all the nceplibs are used in ufs-weather-model. We can't merge the GFS.v16 to develop branch without upp lib.

**Describe the solution you'd like**
Install upp lib on cray at:
/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS_UFS/modules

**Resources and Schedule**
I think Hang Lei can do this work as he installed upp lib in hpc-stack. We need upp lib on cray as soon as possible as physics group is waiting for the model to be updated with GFS.v16 so that they can continue their development.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA can you do this?

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will install it today

**Comment by Hang-Lei-NOAA** [comment]
The upp/10.0.0 is installed on cray.
/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS_UFS/modules
