### ISSUE TITLE
Release version 1.3.0 to match hpc-stack-1.1.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS#173]
We are releasing a new version of hpc-stack, and it involves some new versions of some of the NCEPLIBS. So we need a matching release of NCEPLIBS.

See https://github.com/NOAA-EMC/hpc-stack/issues/72

**Comment by kgerheiser** [comment]
I checked against hpc-stack and the only difference is prod_util and wgrib2

All other libraries are up-to-date

**Comment by edwardhartnett** [comment]
This should be closed when the release is complete...

**Comment by edwardhartnett** [comment]
I have drafted release notes...

**Comment by Hang-Lei-NOAA** [comment]
It has been installed on both dell machines:
module use /usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules
