### ISSUE TITLE
Add NCEPLIBS/2.0.0 on WCOSS_Dell

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/NCEPLIBS#177]
@Hang-Lei-NOAA, 
Please add 'NCEPLIBS/2.0.0' to '/usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS/' on WCOSS_Dell. 
I can find it on WCOSS_Cray but not on WCOSS_Dell. 
It is necessary for SRW App users to build the app on Dell with ease.

**Comment by kgerheiser** [comment]
~It's already installed~

~`/usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS-ufs-v2.0.0/`~

Disregard, I thought I already put it there, but I didn't

**Comment by Hang-Lei-NOAA** [comment]
With Kyle's help, I am installing it now

**Comment by Hang-Lei-NOAA** [comment]
@chan-hoo 
It is installed on
module use /usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS-ufs-v2.0.0/ips-18.0.1.163/impi-18.0.1/modules
for both dell machines.

**Comment by chan-hoo** [comment]
@Hang-Lei-NOAA @kgerheiser  It works! Thank you!

**Comment by climbfuji** [comment]
So is `/usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS-ufs-v2.0.0/ips-18.0.1.163/impi-18.0.1` the top-level directory for the NCEPLIBS-ufs-v2.0.0 installation for the UFS SRW App release on wcoss_dell_p3 and wcoss_cray? I am trying to keep track of those. Thanks!

**Comment by climbfuji** [comment]
Thus far, I had in the spreadsheet for the UFS SRW App (from @kgerheiser and @RatkoVasic-NOAA)
```
wcoss phase3/3.5 | Intel 18.0.1.163 | /usrx/local/nceplibs/dev/NCEPLIBS/cmake/install/NCEPLIBS
wcoss cray       | Intel 19.0.5.281 | /usrx/local/nceplibs/NCEPLIBS/NCEPLIBS-ufs-v2.0.0/intel-19.0.5.281/impi-2019
```
At least on wcoss_cray, the compiler version differs. Can you please clarify?

**Comment by RatkoVasic-NOAA** [comment]
Wcoss phase 3/3.5 is DELL and all worked with intel 18, but on cray it didn't, so Kyle had to bump to Intel 19 in order for build to work.

**Comment by climbfuji** [comment]
> Wcoss phase 3/3.5 is DELL and all worked with intel 18, but on cray it didn't, so Kyle had to bump to Intel 19 in order for build to work.

Ok, thanks. @chan-hoo so you are using Intel 19 on wcoss_cray then?

**Comment by chan-hoo** [comment]
@climbfuji  Yes. Intel/19.0.5.281 on cray.

**Comment by climbfuji** [comment]
> @climbfuji Yes. Intel/19.0.5.281 on cray.

Ok, thanks.
