### ISSUE TITLE
Adding eccodes to NCEPLIBS suite

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/NCEPLIBS#185]
**Is your feature request related to a problem? Please describe.**

Need to modernize our grib library suites with an interface for python. 

**Describe the solution you'd like**

eccodes is an open source library suite that is developed by ECMWF. I want to see if EMC can create a fork and explore supporting it as part of the NCEPLIBS suite

**Resources and Schedule**

TBD

**Comment by edwardhartnett** [comment]
This has been done with hpc-stack and spack-stack. Closing this issue...
