### ISSUE TITLE
Identify changes in ufs-v2.0.0 branch that need to be merged into develop; what is the future of NCEPLIBS-external + NCEPLIBS?

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#187]
The latest public release contains updates that are not in develop. We need to go through those and make sure that whatever is needed/desired finds its way back into develop.

The develop branches of NCEPLIBS-external and NCEPLIBS must be functional together. This is a little difficult, because NCEPLIBS-external is only updated when releases are made - and we have no testing protocol for the two repositories, and no developers assigned to this task.

Or do we abandon NCEPLIBS-external (and NCEPLIBS???) and use hpc-stack instead? What is the long-term vision?

**Comment by edwardhartnett** [comment]
We do not abandon NCEPLIBS-external and NCEPLIBS for hpc-stack.

However, I do not understand this issue. Can you provide a specific example?

Do you mean that one or more of the NCEPLIBS libraries has changes on a v2.0.0 branch that needs to be merged to develop of those libaries?

Or you mean that the versions of some of the NCEPLIBS has changed, so we need to update the versions in the NCEPLIBS repo?

**Comment by climbfuji** [comment]
The issue is that if someone is trying to install NCEPLIBS-external and then NCEPLIBS using "develop" for both, it will not work. And I think it should, but it requires time to update and maintain the two packages.

**Comment by kgerheiser** [comment]
I think we should start automatically testing that. I will bring in changes from `release/public-v2` and create a Github Action to test building NCEPLIBS with NCEPLIBS-external.

**Comment by climbfuji** [comment]
> I think we should start automatically testing that. I will bring in changes from `release/public-v2` and create a Github Action to test building NCEPLIBS with NCEPLIBS-external.

Thanks Kyle, that's great. Please let me know if you need my help with any of this, e.g. NCEPLIBS-external.

**Comment by mkavulich** [comment]
I will just add that I also do not understand the purposes of these different packages. What are the differences in use case between hpc-stack and NCEPLIBS-external/NCEPLIBS?

**Comment by edwardhartnett** [comment]
NCEPLIBS and NCEPLIBS-external are CMake-based builds which were specifically designed to help outside users build our software.

hpc-stack is a non-standard, home-rolled script package that installs our software, and many other packages, on our machines. It is not something we want to distribute or maintain for the user community. It installs mostly other (i.e. non-NOAA) software and we want nothing to do with helping other HPC sites install things like netCDF and PIO. Probably over time we will migrate to a more community-based solution (https://e4s-project.github.io/).

Also, users do not want to read documentation or learn our home-rolled methods, when well-understood and standard methods of distributing and building software exist. Users already understand CMake, they have never heard of, and do not want to learn about, hpc-stack. Nor should they have to.

**Comment by edwardhartnett** [comment]
OK, now that we are moving to spack, this issue can be closed.
