### ISSUE TITLE
Need tag with an updated G2LIB

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/NCEPLIBS#200]
UFS_UTILS uses this tag for its automated Github unit tests - https://github.com/NOAA-EMC/NCEPLIBS/releases/tag/v1.3.0

This tag points to v3.4.1 of G2. That version of G2 has a bug that causes a unit test failure when using the GNU compiler (the Intel tests do not fail, however). 

I ran the unit tests on Hera using G2 v3.4.3. The tests ran successfully.

Can I get a new tag with a new version of G2? Thanks!

**Comment by kgerheiser** [comment]
Done 

See v1.4.0
