### ISSUE TITLE
unable to get certificate for bufr.tar

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/NCEPLIBS#204]
**Describe the bug**
curl is not able to get the certificate to download bufr.tar

**To Reproduce**
[ 97%] (curl) downloading https://ftp.emc.ncep.noaa.gov/static_files/public/bufr.tar
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
test/CMakeFiles/get_bufr_test_data.dir/build.make:72: recipe for target 'test/bufr.tar' failed

**System**
HPC with netcdf and intel compiler 

**Additional context**
I have the same issue with develop branch and latest stable release

**Comment by kgerheiser** [comment]
Could this be on your end, with your local certificates? I don't get this error. Alternatively, `-DBUILD_TESTS=OFF` in Bufr will disable the downloading of these files.

**Comment by mickaelaccensi** [comment]
problem solved by setting environment variable CURL_CA_BUNDLE to the certificate file cacert.pem
