### ISSUE TITLE
Update chgres to latest develop 

### ISSUE THREAD

**Issue by jedwards4b** [NOAA-EMC/NCEPLIBS#21]
Please see https://github.com/ufs-community/ufs-mrweather-app/issues/58#issuecomment-574454266 
Can you please test the latest chgres_cube from develop and if it works merge it to ufs_public_release_v1.0?

**Comment by jedwards4b** [comment]
@climbfuji I tried to do this myself but the cmake interfaces were removed from the develop branch, so I tried to merge ufs_release_v1.0 into develop but that isn't working either.

**Comment by climbfuji** [comment]
Sounds like we need to do a manual update of ufs_release_v1.0 with those changes. @GeorgeVandenberghe-NOAA is it correct that you made the updates to "develop"? Would you be able to make the same updates to "ufs_release_v1.0" that fix the chgres_cube problem?

**Comment by GeorgeVandenberghe-NOAA** [comment]
I suspect it's George Gayno who maintains chgres. Not sure what changes we
are talking about.  I did make changes in the build to get rid of machine
dependencies but never committed them

**Comment by climbfuji** [comment]
> I suspect it's George Gayno who maintains chgres. Not sure what changes we are talking about. I did make changes in the build to get rid of machine dependencies but never committed them
> […](#)

I am sorry. Still confused who is doing what at the East Coast ... @GeorgeGayno-NOAA would you be able to make the same updates to "ufs_release_v1.0" that you made to "develop" to fix the chgres_cube problem for the UFS public release? It seems that the codebases are different enough to prohibit merging. Thank you!

**Comment by jedwards4b** [comment]
I have submitted PR https://github.com/NOAA-EMC/UFS_UTILS/pull/45 with this change in chgres_cube.

**Comment by climbfuji** [comment]
@jedwards4b I will wait for @GeorgeGayno-NOAA to approve, then I can merge it and update the submodule pointer in the umbrella build. Thanks!

**Comment by climbfuji** [comment]
Merged.
