### ISSUE TITLE
Improvement: detect MPI type when building ESMF

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#24]
I am wondering if it is possible to detect the MPI type using cmake and set the cmake variable MPITYPE, required for building ESMF, automatically.

**Comment by kgerheiser** [comment]
I was just looking this up yesterday. I believe you could. If you look at this:

https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindMPI.cmake#L213

`MPI_DETERMINE_LIBRARY_VERSION``
  For each language, find the output of ``MPI_Get_library_version`` and make it available as ``MPI_<lang>_LIBRARY_VERSION_STRING``.
  This information is usually tied to the runtime component of an MPI implementation and might differ depending on ``<lang>``.
  Note that the return value is entirely implementation defined. This information might be used to identify
  the MPI vendor and for example pick the correct one of multiple third party binaries that matches the MPI vendor.
`

Doing that:

```
set(MPI_DETERMINE_LIBRARY_VERSION true)
find_package(MPI REQUIRED)
message(${MPI_C_LIBRARY_VERSION_STRING})
```

I get `Open MPI v4.0.1, package: Open MPI macports@16.local Distribution, ident: 4.0.1, repo rev: v4.0.1, Mar 26, 2019`

**Comment by climbfuji** [comment]
That's great! Let me know which machines I should test on to cover other MPI implementations.

**Comment by climbfuji** [comment]
This is the output/contents of `MPI_C_LIBRARY_VERSION_STRING` for mpich-3.3.1, built with LLVM clang + GNU gfortran on my macOS:
```
MPICH Version:	3.3.1
MPICH Release date:	Wed Jun  5 14:57:33 CDT 2019
MPICH ABI:	13:7:1
MPICH Device:	ch3:nemesis
MPICH configure:	--prefix=/usr/local/llvm --enable-fortran --enable-shared --enable-static
MPICH CC:	clang-9    -O2
MPICH CXX:	clang++-9   -O2
MPICH F77:	gfortran-9   -O2
MPICH FC:	gfortran-9   -O2

```

**Comment by climbfuji** [comment]
This has been implemented.
