### ISSUE TITLE
Dependencies for building jasper (and other parts)

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#25]
On a clean Mac, building jasper fails because libjpeg cannot be found. What is our position on this? Should we require the user to install libjpeg via homebrew (inconsistent with the idea to provide all these thirdparty libraries and only requiring a working compiler and mpi library), or do we want to add it to the thirdparty libraries bundled with the umbrella build?

**Comment by climbfuji** [comment]
Similar story for libpng. I would say we should tell users to install libpng, jpeg and jasper using their OS package manager and not care about them at all.

**Comment by kgerheiser** [comment]
We already include png, so I think we should include jpeg as well, unless we want to remove png and jasper.

**Comment by climbfuji** [comment]
Ok, then something else isn't working correctly, because it either didn't find or build libpng on my Mac.

**Comment by climbfuji** [comment]
Now I see why jasper comes with the NCEPLIBS build, the default version from homebrew doesn't work (the infamouse image.inmem issue). Since users may have this version of jasper installed, we should probably always build it and ignore the OS version.

Now removing homebrew's jpeg, libpng and jasper ... I am working off the old/current CMakeLists.txt that uses external projects. If I added jpeg9d there, you would have to duplicate it in your next-generation CMakeLists.txt. I will probably just install it manually in a temporary directory and wait for your updated build system that ships it.

**Comment by kgerheiser** [comment]
I think the `inmem` problem can be solved by getting rid of the two lines of code that use it in NCEPLIBS-g2. It seems this project (https://github.com/cloudruninc/wps/issues/5) uses the same exact file and had the same exact issue and they just got rid of those two lines here (https://github.com/cloudruninc/wps/commit/a2fad80cc0ff8c1cba259f5aecc1b7393129cc00). 

I don't think they are important.

**Comment by climbfuji** [comment]
The jpeg library is now included. Do we still want to fix the two lines in for jasper?

**Comment by kgerheiser** [comment]
I made the change in NCEPLIBS-g2 to remove the reference to `inmem`, and it made it into the repo with the PRs today, so I say we leave it unless we find that it breaks something.

**Comment by climbfuji** [comment]
Oh great, thanks. I must have missed the change in the g2 library. So we can close this issue?

**Comment by kgerheiser** [comment]
Closing
