### ISSUE TITLE
Misleading log message from top-level CMakeLists.txt

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#26]
On a system w/o hdf5 or netCDF, the cmake call produces the following output:
```
-- Found HDF5: hdf5::hdf5-shared;hdf5::hdf5_fortran-shared (found version "1.10.5") found components: C HL 
-- Could NOT find netCDF (missing NETCDF_DIR)(found version "")
```
The second line is ok, the first line is wrong/misleading. Looking at CMakeCache.txt, it is "finding" the version that is going to be built and installed as part of the NCEPLIBS umbrella build.

**Comment by kgerheiser** [comment]
These libraries are no longer built in this repo
