### ISSUE TITLE
Why not use https for submodule URLs?

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/NCEPLIBS#29]
Is there a particular reason why all of the NOAA-EMC submodules are configured to use the git protocol for cloning instead of https? While one can add ssh keys to their GitHub accounts, it's pretty annoying to have to do that.  It would make things a lot easier and more usable, in my opinion, if everything just referenced the https URL instead.

**Comment by climbfuji** [comment]
Where are you looking at? The instructions on the wiki should already use https, and the correct branches (release/public-v1) also use https throughout.

**Comment by christopherwharrop-noaa** [comment]
I am looking at the master, which is the default branch. You are correct, the release/public-v1 branch does use the https throughout. When the release is final, it will be merged to master I hope?

**Comment by climbfuji** [comment]
Yes, the release branches will be kept for bugfixes specific to release, but master will be updated when the release is finalized.

**Comment by christopherwharrop-noaa** [comment]
Why are their two release v1 branches and how are they different?

**Comment by kgerheiser** [comment]
The branch `release/public-v1` is the official release branch. The branch `ufs_release_v1.0` was where we were doing our development before we finalized the branch names, and will be removed at some point in the near future.

**Comment by christopherwharrop-noaa** [comment]
The wiki says to use `ufs_release_v1.0`.  Where is the development happening now?  In the official release branch? Or the one mentioned in the wiki?  This highlights one of the problem that occurs when you do not also have a "develop" branch that contains stable, non-release, versions of the code and that is updated quickly with tested developments.

**Comment by kgerheiser** [comment]
Development is now happening on the `release/public-v1` branch. We just created and moved to the to that branch yesterday. It was created from  the `ufs_release_v1.0`, and currently they are identical (or mostly identical).

The wiki will be updated today to reflect the most recent developments.

**Comment by christopherwharrop-noaa** [comment]
Ok.  Thank you for clarifying.

**Comment by climbfuji** [comment]
Chris, you may want to know that we have been asked to change names of branches and tags several times over the last few months, faster than we are able to update documentation. The branch names are not up to us to decide, we follow the guidelines from the relevant people in charge of the UFS release. 

Also, it's not written here, but we are supposed to finalize this v1 and create a beta tag by Monday next week. Once this has happened, things will slow done. But right now and for the last weeks, it has been absolutely crazy.
