### ISSUE TITLE
Library install destination is hard-coded to lib

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#36]
This issue is for the long-term development, not for the upcoming UFS release in March/February 2020.

The NCEPLIBS all have hardcoded library installation locations (and same for binary etc):
```
install(TARGETS ${lib_name}
  EXPORT ${PROJECT_NAME}-config
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib) 
```
Shouldn't these be matching the host's library installation directories, e.g. use `${CMAKE_INSTALL_LIBDIR}` instead of `lib`?

**Comment by aerorahul** [comment]
@climbfuji Is this issue still relevant?  The library installation directories are relative to `CMAKE_INSTALL_PREFIX`, no?

**Comment by kgerheiser** [comment]
@aerorahul `${CMAKE_INSTALL_LIBDIR}` which is usually `lib`, but could be `lib64` for example. 

I'm not sure the exact mechanics, but I think certain Linux distros do it like that.

**Comment by edwardhartnett** [comment]
Is this going to happen? If so, is it going to be in the 1.3.0 release?

**Comment by climbfuji** [comment]
I won't be able to work on this, but all hardcoded `lib` directories should be replaced by `${CMAKE_INSTALL_LIBDIR}`.

We could go further and do this for all others as well (`bin`, `share`), but because all systems use the same names for those I consider this an overkill.

**Comment by kgerheiser** [comment]
It's easy enough. Some libraries (wgrib2, maybe some others) already do this. Just have to make it consistent.

**Comment by edwardhartnett** [comment]
I believe this change was applied everywhere. I will close this issue.
