### ISSUE TITLE
Debug Build

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS#37]
It would be nice to have a debug build where we set: `-g -O0 -Wall -fbacktrace -fcheck=all` and the Intel equivalents

**Comment by climbfuji** [comment]
It would be! I am just worried that we break something if we rush this in before the release. What do you think?

**Comment by kgerheiser** [comment]
I agree. I'm not in a rush to make large changes right now, but once we have a working, tested build this would be nice to have and it would be pretty easy

**Comment by climbfuji** [comment]
@kgerheiser @mark-a-potts @aerorahul there was a question today at the UFS code manager meeting whether we have a debug mode for the NCEPLIBS. Is this something we want to provide in the near future? There is an effort to enable a debug mode for every component used by the UFS (and the UFS build system will then switch to use the debug version of external libraries so as NCEPLIBS). Thanks!

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @junwang-noaa FYI

**Comment by aerorahul** [comment]
> @kgerheiser @mark-a-potts @aerorahul there was a question today at the UFS code manager meeting whether we have a debug mode for the NCEPLIBS. Is this something we want to provide in the near future? There is an effort to enable a debug mode for every component used by the UFS (and the UFS build system will then switch to use the debug version of external libraries so as NCEPLIBS). Thanks!

In cmake you can build with DEBUG as your build type.
I don't think all the libraries have all the appropriate DEBUG flags currently, but I don't see why that cannot be added.
I don't see why would any UFS component developer want to deep dive in debugging NCEPlibs.
Also, is this the right path? Are they going to build all the external libraries e.g. esmf, netcdf, hdf5, etc. in debug mode? To me NCEPlibs are no different than those.
But to answer your question, we can build NCEPlibs in debug mode.

**Comment by climbfuji** [comment]
Certainly they do for ESMF (they have already done, this is incredibly useful). Others may be added if needed. But NCEPLIBS is certainly on the wishlist.

**Comment by edwardhartnett** [comment]
Is this work complete? Are there still some NCEPLIBS without a debug build? If so, which ones?

**Comment by edwardhartnett** [comment]
I believe all NCEPIBS can now build in Debug mode. I will close this issue.
