### ISSUE TITLE
Default install location and inability to change it

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#5]
Without specifying any install location, the NCEPlibs umbrella build tries to install everything in `/usr/local`. This is an absolute no-go. People may not want the curl, hdf5, ... that come with the umbrella build to go there and preserve their own/default dev environment The NCEPlibs umbrella build should be entire self-consistent and not interfere with any default locations. Thus, the default installation location should either be none (i.e. raising an error if the user does not specify it), or the build directory from which cmake and make are called.

I tried using (branch ufs_release_1.0)
```
cmake -DCMAKE_INSTALL_PREFIX=$PWD ../ 2>&1 | tee log.cmake
```
and this was passed correctly to curl and hdf5 during the make call. I didn't get further, because the netCDF build failed (see previously reported isse https://github.com/NOAA-EMC/NCEPLIBS/issues/2 - we need to fix this asap)

**Comment by kgerheiser** [comment]
I noticed this too. I think we should make the default install directory be `CMAKE_BINARY_DIR/Install`

**Comment by kgerheiser** [comment]
I made a PR that addresses this. It sets the install path to `CMAKE_BINARY_DIR/install".

**Comment by climbfuji** [comment]
Great, thank you. I am working my way through the build on macOS, and I will have a PR ready soon for netcdf-fortran and other issues I encounter(ed) along the way.
