### ISSUE TITLE
Missing -fPIC flag for all NCEPLIBS-*/EMC_post/UFS_UTILS

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#67]
The NCEPLIBS cannot be linked into dynamic libraries, because they are missing the `-fPIC` flags during compilation/linking.

**Comment by kgerheiser** [comment]
So, what do we have to do? Do we have to add that flag to every repo?

**Comment by aerorahul** [comment]
No. If you build a dynamic library, -fPIC is added automatically. We are building static libraries. 
add_library(libName STATIC sources)

**Comment by aerorahul** [comment]
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

But, CMAKE_POSITION_INDEPENDENT_CODE property is set by default for SHARED targets, there is no need to set it explicitly

**Comment by climbfuji** [comment]
> set(CMAKE_POSITION_INDEPENDENT_CODE ON)
> 
> But, CMAKE_POSITION_INDEPENDENT_CODE property is set by default for SHARED targets, there is no need to set it explicitly

We should try this as long as we can (the only application of this I am aware of at the moment is the "old dynamic CCPP build", which will be removed soon), or decide to not support linking static NCEP libraries to a dynamic library *.so / *.dylib.

**Comment by aerorahul** [comment]
@climbfuji Are you advocating we build shared libraries for NCEPLIBS? 
There is no need to add the line
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`
if we are building static NCEPLIBS.  And by that I am excluding applications under `UFS_UTILS`, `NCEP_POST`, etc.
That property is set by default if shared libraries are being built.
Either way, there is no need to add that line in any of the `CMakeLists.txt`

If desired, we can build both static and shared versions of the NCEPLIBS.  That can be achieved without too much work.  But, I don't see any advantage of using shared NCEPLIBS.

Can you elaborate what you want to try?

**Comment by climbfuji** [comment]
> @climbfuji Are you advocating we build shared libraries for NCEPLIBS?
> There is no need to add the line
> `set(CMAKE_POSITION_INDEPENDENT_CODE ON)`
> if we are building static NCEPLIBS. And by that I am excluding applications under `UFS_UTILS`, `NCEP_POST`, etc.
> That property is set by default if shared libraries are being built.
> Either way, there is no need to add that line in any of the `CMakeLists.txt`
> 
> If desired, we can build both static and shared versions of the NCEPLIBS. That can be achieved without too much work. But, I don't see any advantage of using shared NCEPLIBS.
> 
> Can you elaborate what you want to try?

Right now there is one use case only, and as I said it will go away. But if we can easily create both, then why not? Any negative implications other than build systems mistakenly picking up the wrong = shared libraries instead of the static libraries? Or use a CMake option to enable it explicitly if needed?

The use case is: the dynamic CCPP build first builds `libccpp.{so,dylib}` and `libccppphys.{so,dylib}`, which later gets linked to the executable. The latter `libccppphys.{so,dylib}` links to three of the NCEPLIBS (static if those are the only available). It is this linker step that fails, because it complains that the static libraries have not been built with `-fPIC`. In my understanding, `-fPIC` is only required when you build static executables that get linked to a dynamic object (which needs to be position independent code).

**Comment by aerorahul** [comment]
This has raised its ugly head again.
When linking the  UFS-weather-model as a library with applications in JEDI, we get this error, especially for sp and w3emc|nco.

It probably would be safe to just force `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` in all of the NCEPLIBS-xyz to be consistent.

**Comment by edwardhartnett** [comment]
Has this been completed? Should this issue be closed?

**Comment by edwardhartnett** [comment]
Has this been completed? Should this issue be closed?

**Comment by edwardhartnett** [comment]
We are doing an upgrade of all shared/static builds in the next release cycle of all NCEPLIBS. I will close this issue when that is complete.

**Comment by climbfuji** [comment]
@edwardhartnett I believe that all the hard work on the NCEPLIBS fixed this issue by now?
