### ISSUE TITLE
Add a message when library is found

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS#75]
What do you think of adding a message when the package is found, the same as when zlib, or PNG is found, for example:

> -- Found JPEG: /Users/KIG/dev/gnu-9.3.0/jpeg/9.1.0/lib/libjpeg.dylib (found version "90")

Then in the package config file we put:

```
get_target_property(g2_location g2::g2_4 LOCATION)
message(STATUS "Found g2: ${g2_location}")
```

And pre-config it would look like:

```
get_target_property(location @PROJECT_NAME@::@PROJECT_NAME@_4 LOCATION)
message(STATUS "Found @PROJECT_NAME@: ${location}")
```

Thoughts @aerorahul

**Comment by aerorahul** [comment]
@kgerheiser 
I think this is a good idea to notify the user that a package was requested and found along with the version number.

**Comment by kgerheiser** [comment]
Any idea why the version doesn't show up? I query the property `VERSION` and it isn't set, but there's the `g2-config-version.cmake` which has the version. And the version is passed to `configure_file` too. It seems like it should be available somehow. Should it be a configure variable, like `set(version @PROJECT_VERSION@)`?

**Comment by kgerheiser** [comment]
Done

**Comment by aerorahul** [comment]
@kgerheiser 
Sorry for the late follow up.
We are creating a basic package version file.  You just need to include it in your package-config file. It sets the variable `PACKAGE_VERSION`
For e.g.
```
include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@-config-version.cmake")
message(STATUS "Found @PROJECT_NAME@ VERSION  ${PACKAGE_VERSION}")
```

**Comment by kgerheiser** [comment]
Oh, ok that makes sense
