### ISSUE TITLE
Add bufrlib to the NCEPLIBS umbrella build.

### ISSUE THREAD

**Issue by mark-a-potts** [NOAA-EMC/NCEPLIBS#81]
I am currently updating the GSI build system to work with the new NCEPLIBS builds, but it needs bufrlib. If we could get it added in to the umbrella build, that would be great.

**Comment by aerorahul** [comment]
@mark-a-potts 
The current cmake bufrlib compilation in the public release [here](https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/release/public-v1/CMakeLists.txt) has a little too many peculiarities.  Can someone explain what the different `kinds` are [here](https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/4b4dfaeaa3793c86ea25b9417f381f518a235cdf/CMakeLists.txt#L86) and if they are all needed? Or would the ones under [here](https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/4b4dfaeaa3793c86ea25b9417f381f518a235cdf/CMakeLists.txt#L84) suffice?  I suspect those are all that are needed. 

Also, what are `double`, `doubleDA` and `supersize`?  Are these needed? 

Where are these all used?  Can anyone tag Jeff Ator?
