### ISSUE TITLE
WARNINGS during NCEPLIBS umbrella build

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS#89]
Some NCEPLIBS do not depend on `C` or on `Fortran` compiler.
Some NCEPLIBS have no use for the `ENABLE_TESTS` option. 

During configuration, all NCEPLIBS in the loop are provided the following cmake arguments:

```
"-DENABLE_TESTS=${ENABLE_TESTS}"
"-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
"-DCMAKE_Fortran_COMPILER=${CMAKE_Fortran_COMPILER}"
```

which lead to the annoying warnings such as:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_TESTS
```

**Comment by kgerheiser** [comment]
The only way to fix this, I think, would be to have each project have its own ExternalProject_Add, instead of a loop. 

On one hand I can see the benefit of that for more fine-grain control over build options, but on the other it's really repetitive for the most part.

**Comment by aerorahul** [comment]
ugh! Ok. We can live with it.
