### ISSUE TITLE
Use correct environment variables to detect ESMF

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/NCEPLIBS#9]
(referring to ufs_release_1.0)

The `CMakeLists.txt` logic looks for `ESMF_LIB` to detect if ESMF is already installed on the system. The official way to detect and set ESMF (per ESMF developer guidance) is to set `ESMFMKFILE`, e.g.
```
ESMFMKFILE="/usr/local/gnu/esmf-8.0.0/lib/esmf.mk"
```
`CMakeLists.txt` should only check for this environment variable, nothing else.

We should also check that for all other prerequisites, the standard/official variables are checked (e.g. I believe that the standard env. variable for netCDF is `NETCDF`, not `NETCDF_DIR` or `NETCDF_ROOT` - please correct me if I am wrong). A similar discussion is taking place between the ufs-weather-model developers, and the agreement is that the software/build system should only check for the standard/official environment variables. If the system deviates, this should be fixed or documented on what to set instead of providing workarounds in the build system.

@DusanJovic-NOAA @arunchawla-NOAA FYI

**Comment by kgerheiser** [comment]
I've got a fix

**Comment by climbfuji** [comment]
Me too - I will see what you have and adjust my proposed changes to ufs_release_1.0 if needed.

I am using the findESMF.cmake package that comes with ESMF.

**Comment by climbfuji** [comment]
Fixed by https://github.com/NOAA-EMC/NCEPLIBS/pull/12
