### ISSUE TITLE
WGRIB2 openmp not enabled.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS#95]
The umbrella build option for OpenMP is `-DOPENMP=ON|OFF`.
WGRIB2 expects `-DUSE_OPENMP`.

A change is necessary either here or in wgrib2 feature/cmake branch.

**Comment by kgerheiser** [comment]
Fixed in wgrib2. Changed the option from USE_OPENMP to OPENMP to be consistent

**Comment by kgerheiser** [comment]
I'll wait until I update the tag here to close
